### ISSUE TITLE
KeyError: 'x-object-downloads'

### ISSUE THREAD

**Issue by MikeVL** [go1dshtein/selectel-api#2]
```
Traceback (most recent call last):
  ...
    if cdn_storage.exists(cdn_filename):
  File "/usr/local/lib/python2.7/dist-packages/django_selectel_storage/storage.py", line 98, in exists
    self.container.info(self._name(name))
  File "/usr/local/lib/python2.7/dist-packages/selectel/storage.py", line 234, in method
    return fn(self.name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/selectel/storage.py", line 15, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/selectel/storage.py", line 190, in info
    "downloads": int(r.headers["X-Object-Downloads"])
  File "/usr/local/lib/python2.7/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-object-downloads'
```

**Comment by go1dshtein** [comment]
tests does not pass. service can be unstable. it requires further investigation

```
ERROR: test_copy (tests_storage.TestsStorage)
----------------------------------------------------------------------
Traceback (most recent call last):
   File "/Users/rosso/Documents/selectel-api/tests/tests_storage.py", line 136, in tearDown
     self.storage.drop("unittest", force=True, recursive=True)
   File "/Users/rosso/Documents/selectel-api/.tox/py33/lib/python3.3/site-packages/selectel/storage.py", line 15, in wrapper
      return fn(*args, **kwargs)
   File "/Users/rosso/Documents/selectel-api/.tox/py33/lib/python3.3/site-packages/selectel/storage.py", line 217, in drop
      r.raise_for_status()
   File "/Users/rosso/Documents/selectel-api/.tox/py33/lib/python3.3/site-packages/requests/models.py", line 851, in raise_for_status
      raise HTTPError(http_error_msg, response=self)
   requests.exceptions.HTTPError: 409 Client Error: Conflict

ERROR: test_info (tests_storage.TestsStorage)
---------------------------------------------------------------------- 
Traceback (most recent call last):
   File "/Users/rosso/Documents/selectel-api/tests/tests_storage.py", line 73, in test_info
     info = self.storage.info("unittest")
   File "/Users/rosso/Documents/selectel-api/.tox/py33/lib/python3.3/site-packages/selectel/storage.py", line 15, in wrapper
     return fn(*args, **kwargs)
   File "/Users/rosso/Documents/selectel-api/.tox/py33/lib/python3.3/site-packages/selectel/storage.py", line 179, in info
     "tx": int(r.headers["X-Transfered-Bytes"]),
   File "/Users/rosso/Documents/selectel-api/.tox/py33/lib/python3.3/site-packages/requests/structures.py", line 54, in __getitem__
     return self._store[key.lower()][1]
   KeyError: 'x-transfered-bytes'
```

**Comment by MikeVL** [comment]
This can help to resolve this issue

https://github.com/dimetris/selectel-api/commit/8fc0cf6d72712aacf1fa66876ee3df6547ce9946

**Comment by go1dshtein** [comment]
@MikeVL, yes, thanks, I've fixed it in this way.

but seems selectel's server returns response code before requests actually done.
